version: '3.8'

services:
  postgres:
    image: postgres-multidb
    container_name: postgres
    restart: always
    environment:
      POSTGRES_MULTIPLE_DATABASES: springsandboxjava,springsandboxkotlin
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

  mongo:
    image: mongo:4.4.1
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
      - mongo-config:/data/configdb

  fluentd:
    image: fluentd:dev
    container_name: fluentd
    restart: always
    depends_on:
      - mongo

  terracotta:
    image: terracotta/terracotta-server-oss:5.6.4
    container_name: terracotta
    hostname: terracotta

  spring-gateway-sandbox:
    image: maven:3.6.3-openjdk-8
    container_name: spring-gateway-sandbox
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - 8080:8080
    volumes:
      - maven-data:/root/.m2
      - ${SANDBOX_BASE_DIR}/spring-gateway-sandbox/:/src
    working_dir: /src
    command: mvn spring-boot:run

  spring-sandbox-java:
    image: maven:3.6.3-openjdk-8
    container_name: spring-sandbox-java
    depends_on:
      - fluentd
      - postgres
    environment:
      SPRING_PROFILES_ACTIVE: docker
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: springsandboxjava
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - maven-data:/root/.m2
      - ${SANDBOX_BASE_DIR}/spring-sandbox-java/:/src
    working_dir: /src
    command: mvn spring-boot:run

  spring-sandbox-kotlin:
    image: gradle:6.7.0-jdk8
    container_name: spring-sandbox-kotlin
    depends_on:
      - fluentd
      - postgres
    environment:
      SPRING_PROFILES_ACTIVE: docker
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: springsandboxkotlin
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - gradle-data:/home/gradle/.gradle
      - ${SANDBOX_BASE_DIR}/spring-sandbox-kotlin/:/home/gradle/project
    working_dir: /home/gradle/project
    command: gradle bootRun

networks:
  default:
    name: dev-sandbox

volumes:
  postgres-data:
    name: postgres-data
  mongo-data:
    name: mongo-data
  mongo-config:
    name: mongo-config
  maven-data:
    name: maven-data
  gradle-data:
    name: gradle-data
