version: '3.8'

services:
  mysql:
    image: mysql:8.0.27
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: public
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

networks:
  default:
    name: databases-network

volumes:
  mysql-data:
    name: mysql-data
