version: '3.9'

services:
  mongo:
    image: mongo:6.0.4
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
      - mongo-config:/data/configdb

networks:
  default:
    name: databases-network

volumes:
  mongo-data:
    name: mongo-data
  mongo-config:
    name: mongo-config
