version: '3.9'

services:
  fluentd:
    image: fluentd:v1.14.0-debian-1.0
    build: ../../../build/fluentd
    container_name: fluentd
    restart: always

networks:
  default:
    name: monitoring-network
