version: '3.8'

services:
  fluentd:
    image: fluentd:v1.12.1-debian-1.0
    build: ../../../build/fluentd
    container_name: fluentd
    restart: always

networks:
  default:
    name: monitoring-network
