version: '3.8'

services:
  nimbus:
    image: storm:2.2.0
    container_name: nimbus
    hostname: nimbus
    restart: always
    depends_on:
      - zoo1
      - zoo2
      - zoo3
    ports:
      - 6627:6627
    volumes:
      - nimbus-data:/data
      - nimbus-logs:/logs
      - ${SANDBOX_BASE_DIR}/deployment/apache-cluster/storm/storm.yaml:/conf/storm.yaml
    command: storm nimbus

  supervisor1:
    image: storm:2.2.0
    container_name: supervisor1
    hostname: supervisor1
    restart: always
    depends_on:
      - nimbus
      - zoo1
      - zoo2
      - zoo3
    volumes:
      - supervisor1-data:/data
      - supervisor1-logs:/logs
      - ${SANDBOX_BASE_DIR}/deployment/apache-cluster/storm/storm.yaml:/conf/storm.yaml
    command: storm supervisor

  supervisor2:
    image: storm:2.2.0
    container_name: supervisor2
    hostname: supervisor2
    restart: always
    depends_on:
      - nimbus
      - zoo1
      - zoo2
      - zoo3
    volumes:
      - supervisor2-data:/data
      - supervisor2-logs:/logs
      - ${SANDBOX_BASE_DIR}/deployment/apache-cluster/storm/storm.yaml:/conf/storm.yaml
    command: storm supervisor

  ui:
    image: storm:2.2.0
    container_name: ui
    hostname: ui
    restart: always
    depends_on:
      - nimbus
      - zoo1
      - zoo2
      - zoo3
    ports:
      - 8080:8080
    volumes:
      - ui-data:/data
      - ui-logs:/logs
      - ${SANDBOX_BASE_DIR}/deployment/apache-cluster/storm/storm.yaml:/conf/storm.yaml
    command: storm ui

networks:
  default:
    name: apache-cluster-network

volumes:
  nimbus-data:
    name: nimbus-data
  nimbus-logs:
    name: nimbus-logs
  supervisor1-data:
    name: supervisor1-data
  supervisor1-logs:
    name: supervisor1-logs
  supervisor2-data:
    name: supervisor2-data
  supervisor2-logs:
    name: supervisor2-logs
  ui-data:
    name: ui-data
  ui-logs:
    name: ui-logs
