version: '3.8'

services:
  spring-gateway-sandbox:
    image: maven:3.8.3-openjdk-8
    container_name: spring-gateway-sandbox
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - 8080:8080
    volumes:
      - maven-data:/root/.m2
      - ${SANDBOX_BASE_DIR}/spring-gateway-sandbox/:/src
    working_dir: /src
    command: mvn spring-boot:run

  spring-sandbox-java:
    image: maven:3.8.3-openjdk-8
    container_name: spring-sandbox-java
    environment:
      SPRING_PROFILES_ACTIVE: docker
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: springsandboxjava
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - maven-data:/root/.m2
      - ${SANDBOX_BASE_DIR}/spring-sandbox-java/:/src
    networks:
      - default
      - databases
      - monitoring
      - cache
    working_dir: /src
    command: mvn spring-boot:run

  spring-sandbox-kotlin:
    image: gradle:7.3.0-jdk8
    container_name: spring-sandbox-kotlin
    environment:
      SPRING_PROFILES_ACTIVE: docker
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: springsandboxkotlin
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - gradle-data:/home/gradle/.gradle
      - ${SANDBOX_BASE_DIR}/spring-sandbox-kotlin/:/home/gradle/project
    networks:
      - default
      - databases
      - monitoring
      - cache
    working_dir: /home/gradle/project
    command: gradle bootRun

  nodejs-sandbox:
    image: node:17.1.0-alpine
    container_name: nodejs-sandbox
    volumes:
      - ${SANDBOX_BASE_DIR}/nodejs-sandbox/:/src
    working_dir: /src
    command: npm start

  reactjs-sandbox:
    image: node:17.1.0-alpine
    container_name: reactjs-sandbox
    ports:
      - 3000:3000
    volumes:
      - ${SANDBOX_BASE_DIR}/reactjs-sandbox/:/src
    working_dir: /src
    command: npm start

networks:
  default:
    name: dev-sandbox
  databases:
    external: true
    name: databases-network
  monitoring:
    external: true
    name: monitoring-network
  cache:
    external: true
    name: cache-network

volumes:
  maven-data:
    name: maven-data
  gradle-data:
    name: gradle-data
