version: '3.8'

services:
  postgres:
    image: postgres:13.2-alpine
    container_name: postgres
    restart: always
    environment:
      POSTGRES_MULTIPLE_DATABASES: springsandboxjava,springsandboxkotlin
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ${SANDBOX_BASE_DIR}/deployment/databases/postgres/docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d

networks:
  default:
    name: databases-network

volumes:
  postgres-data:
    name: postgres-data
