version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3.9.9-management
    container_name: rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

networks:
  default:
    name: messaging-network

volumes:
  rabbitmq-data:
    name: rabbitmq-data
