version: '3.8'

services:
  grafana:
    image: grafana/grafana:8.2.3
    container_name: grafana
    restart: always
    ports:
      - 3000:3000
    volumes:
      - grafana-data:/var/lib/grafana
      - grafana-config:/etc/grafana

networks:
  default:
    name: monitoring-network

volumes:
  grafana-data:
    name: grafana-data
  grafana-config:
    name: grafana-config
