version: '3.9'

services:
  kibana:
    image: docker.elastic.co/kibana/kibana:8.6.2
    container_name: kibana
    restart: always
    ports:
      - 5601:5601

networks:
  default:
    name: elastic-stack-network
