version: '3.8'

services:
  kibana:
    image: docker.elastic.co/kibana/kibana:7.13.1
    container_name: kibana
    restart: always
    ports:
      - 5601:5601

networks:
  default:
    name: elastic-stack-network
